### ISSUE TITLE
dbTweets.js saving issues

### ISSUE THREAD

**Issue by Logarythms** [Rostlab/JS16_ProjectD_Group5#43]
On the unified-twitter-api branch:
dbTweets.js only saves one Tweet to the database and fails afterwards. The cause of this might be with me but I'm unable to identify something specific from the logs.

When running client.js calling the Rest-API:

_Connected to Database!
Tweet saved!
Error saving tweet
[...]
Error saving tweet

/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: server ds023438-a.mlab.com:23438 sockets closed
    at Server.destroy (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongodb-core/lib/topologies/server.js:824:47)
    at Server.close (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongodb/lib/server.js:378:17)
    at Db.close (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongodb/lib/db.js:350:19)
    at NativeConnection.doClose (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:218:11)
    at NativeConnection.Connection._close (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/connection.js:565:12)
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/connection.js:536:11
    at new Promise.ES6 (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/promise.js:45:3)
    at NativeConnection.Connection.close (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/connection.js:535:10)
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/db/dbTweets.js:50:16
    at model.<anonymous> (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/document.js:1822:20)
    at next_ (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/hooks-fixed/hooks.js:89:34)
    at fnWrapper (/Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/hooks-fixed/hooks.js:186:18)
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/model.js:292:13
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/model.js:227:5
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongoose/lib/model.js:136:7
    at /Users/camillemainz/dev/js_seminar/JS16_ProjectD_Group5/node_modules/mongodb/lib/collection.js:504:5_

**Comment by Logarythms** [comment]
(All the changes in develop as of tonight are of course merged into the unified-twitter-api branch)

**Comment by Logarythms** [comment]
The Streaming-API also only seems to save the first incoming tweet, although it doesn't throw any errors afterwards. I don't know if this is a fuckup on my side or an issue with the database :D

**Comment by kajo404** [comment]
Ok so far I found several issues that might be the cause of this. 
1. I would appreciate it if you could use the API I made to connect to the database and save tweets. see here https://github.com/Rostlab/JS16_ProjectD_Group5/blob/unified-twitter-api/db/dbTweets.js
   There will be a pull request today that makes tweet ID unique, so keep that in mind when testing
2. When you save your tweet you dont fill out all the fields marked required in the Schema.

**Comment by Logarythms** [comment]
By API you mean the saveTweet function in dbTweets.js right? Because that's what I'm using:
https://github.com/Rostlab/JS16_ProjectD_Group5/blob/unified-twitter-api/logic/twitterAPI.js

And as far as I know all the schema-fields are also filled out.

Are you sure you checked the right file of mine? :D

**Comment by kajo404** [comment]
Okay thanks for removong the clutter, I was indeed looking at the wrong file.

```
var jsonTweet = getTweetAsJSON(tweet, characterName, characterID);
dbTweets.saveTweet(jsonTweet);
```

look at this code example. I think here is a problem. The function call is asynchronous and jsonTweet will have the value 'undefined' when being used in dbTweets.save(). dbTweets doesn't wait for the result of the getTweetAsJSON result. Functions are asynchronous by nature in JavaScript I think

**Comment by Logarythms** [comment]
Well I tried building the JSON in the getStream itself instead of using getTweetAsJSON, but I still get the same result. 
Also when I do a console.log(newTweet) in dbTweets.js, the new Tweets all exist correctly. But still only the first tweet each session is saved, both for the Streaming and for Rest API.

**Comment by Logarythms** [comment]
There was a bug in dbTweets.js that is now fixed
